global:
  scrape_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'cadvisor'
  static_configs:
  - targets: ['localhost:8800']

- job_name: 'prometheus'
  file_sd_configs:
  - files:
    - /prometheus/*.json

- job_name:       'dadvisor'
  metrics_path: /dadvisor/metrics
  static_configs:
    - targets: ['localhost:5000']
