global:
  scrape_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:8800', 'localhost:5000/dadvisor']

  file_sd_configs:
  - files:
    - /prometheus/*.json
