global:
  scrape_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'cadvisor'
  static_configs:
  - targets: ['localhost:8080']

- job_name: 'promadvisor'
  metrics_path: '/prometheus/federate'

  params:
    'match[]':
      - '{job=~".*advisor"}'  # match everything with *advisor

  file_sd_configs:
  - files:
    - /prometheus-federation.json

- job_name:       'dadvisor'
  metrics_path: /dadvisor/metrics
  static_configs:
    - targets: ['localhost:5000']
