global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:8800']

  file_sd_configs:
  - files:
    - /prometheus/*.json
