{
 "title": "dAdvisor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Container Topology Inspection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count({__name__=~\"docker_container_.*\"})"
    }
   ]
  },
  {
   "title": "Number of peers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count({__name__=~\"peer_.*\", exported_instance=\"\"})"
    }
   ]
  },
  {
   "title": "Container-graph",
   "type": "grafana-container-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 5 },
   "valueName": "current",
   "targets": [
    { "expr": "docker_container" },
    { "expr": "bytes_send_total" },
    {
     "expr": "avg_over_time(rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\", name!=\"dadvisor\"}[1m])[1h:1h])",
     "legendFormat": "container_utilization"
    },
    { "expr": "default_host_price_info" },
    {
     "expr": "sum_over_time(avg_over_time(rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\", name!=\"dadvisor\"}[1m])[1h:1h]) [1h:1h])",
     "legendFormat": "container_total_util"
    },
    { "expr": "waste_container" },
    { "expr": "waste_container_total", "legendFormat": "total_waste" }
   ]
  }
 ]
}